### ISSUE TITLE
Error in calculation for run_at_sunset with offset

### ISSUE THREAD

**Issue by stowers95120** [hassio-addons/app-appdaemon#12]
# Problem/Motivation

> Where you use run_at_sunset with a negative offset (eg -900) the first time the trigger executes at the expected time, but it resets the trigger to two days hence.

## Expected behavior

> When the trigger executed at 15mins before sunset on 2/25 I expected to look in the appdaemon admin console and see the trigger set for 15mins before sunset on 2/26. Instead it was set for 2/27.

For run_at_sunset with no offset, the expected behavior is observed

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Hi!

Thanks for opening up a report, however, this is not related to the add-on, but AppDaemon itself. Please report the issue with AppDaemon.

Thanks! 👍
