### ISSUE TITLE
listen_state not getting invoked when sensor gets update with same value

### ISSUE THREAD

**Issue by FatBeard** [hassio-addons/app-appdaemon#120]
# Problem/Motivation

"listen_state(self.state_change, sensor)" not calling python script when sensor gets updated with same value. If the value changes, the script runs fine.

## Expected behavior

Even though the value remains the same, the fact that the sensor has been updated should still invoke the python script

## Actual behavior

The script does not get invoked

## Steps to reproduce

Create a script which hooks on "listen_state(self.state_change, sensor)"
Update the value of the entity in developer tools with the same value as the sensor already

(I'm using an esp_home configured entity, but i don't think esphome is the problem as i can recreate the issue when updating the sensor in developer tools in HA)

**Comment by frenck** [comment]
Hi there @FatBeard 👋 

Thanks for opening an issue, however, add-ons wrap existing applications, in this case appdaemon. We don't develop appdaemon itself. Merely the add-on package.

If you have an issue with AppDaemon itself, please report that with the AppDaemon project. If they fix and release a new version, the add-on will get that update as well.

Thanks! 👍 

../Frenck
