### ISSUE TITLE
using await self.turn_on in an async method results in wonkiness

### ISSUE THREAD

**Issue by marklio** [hassio-addons/app-appdaemon#13]
# Problem/Motivation

> I was trying to use await self.turn_on to turn on some lights in an asynchronous task, and I kept getting exceptions

## Expected behavior

> await self.turn_on("entityname") should behave basically identically to await self.call_service("home_assistant/turn_on", entity_id= "entityname")

## Actual behavior

> using turn_on kept giving me exceptions. I'm not super familiar with python's async mechanics, but when I use call_service, it works fine

## Steps to reproduce

> use self.create_task(test()) to create a task over a coroutine in initialization of an AD app. In the coroutine, use await self.turn_on. In my example, I also had some await self.sleep(1) calls and some self.log calls, but that doesn't seem to matter much.

## Proposed changes

> Unfortunately, I don't know enough about python to know what's wrong. Thanks for taking a look.

**Comment by frenck** [comment]
Hi!

Thanks for opening up a report, however, this is not related to the add-on, but AppDaemon itself. Please report the issue with AppDaemon.

Thanks! 👍
