### ISSUE TITLE
call_service() ValueError: Invalid Service Name

### ISSUE THREAD

**Issue by jarekgrzabel** [hassio-addons/app-appdaemon#139]
Hi,

I have integration with HA. All running on the latest versions (stable). I'm running it through HAOS with supervisor. Everything installed through supervisor add-ons. 
I've had this integration working and it was sending notifications to my mobile HA app and it was working perfectly until yesterday. I haven't changed anything but suddenly I'm getting an error:

```
File "/usr/lib/python3.8/site-packages/appdaemon/adapi.py", line 1539, in _check_service
    raise ValueError("Invalid Service Name: {}".format(service))
ValueError: Invalid Service Name: notify.mobile_app_jarek
```
My code isn't advanced, it simply sends the notification:
```
        self.call_service("notify.mobile_app_jarek", title="test", message="test message!")
```
When I invoke this from HA directly it works fine. When I run it from AD it doesn't work at all drops an error that it doesn't know that service name. I ran a debug at startup and I can see that the service is there:
```
....
{'namespace': 'default', 'domain': 'notify', 'service': 'mobile_app_jarek'}, 
....
```

I have no idea why it stopped working. Any hints are really appreciated.

**Comment by frenck** [comment]
Hi there @jarekgrzabel 👋 

This is a bit out of scope for the add-on, as this is a question about AppDaemon itself, that is running inside of the add-on. Add-ons wrap existing software, in this case: AppDaemon.

I would recommend asking this question with the AppDaemon project, you are more likely to find an answer to your question in their community.

../Frenck
