### ISSUE TITLE
Leap year but. Please update appdaemon version

### ISSUE THREAD

**Issue by samnewman86** [hassio-addons/app-appdaemon#14]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
No content in issue.
Closing, feel free to open a new one with content.
