### ISSUE TITLE
Latest release

### ISSUE THREAD

**Issue by Jurgenn22** [hassio-addons/app-appdaemon#147]
# Problem/Motivation

> Latest release broke dashboard vieuw on Ipad with safari and chrome browser, showing only empty widgets.

## Expected behavior

> That dashboard on the ipad on safari and chrome works as before.

## Actual behavior

> dashboard vieuw on Ipad with safari and chrome browser, showing only empty widgets. When a snapshot from the addon is restored with the previous release, everything works as before.

## Steps to reproduce

> 

## Proposed changes

> 
>

**Comment by sinclairpaul** [comment]
Likely duplicate of #146
