### ISSUE TITLE
Samsung

### ISSUE THREAD

**Issue by safadig** [hassio-addons/app-appdaemon#152]
# Problem/Motivation

> AppDaemon Dashboard Stopped Loading on Samsung Digital Signage Display

## Expected behavior

> Dashboard to load as before. Same Dashboard Loads fine on Computer Browser

## Actual behavior

> Only Empty Panels load
## Steps to reproduce

> Open an AppDaemon Dasboard on Samsung digital Display

## Proposed changes

>Worked prior to latest update

**Comment by sinclairpaul** [comment]
#146 #147 

It is an upstream issue
