### ISSUE TITLE
What happened to the Appdeamon dashboards on old iPad?

### ISSUE THREAD

**Issue by Kouwe-sudo** [hassio-addons/app-appdaemon#156]
# Problem/Motivation

> What happened to the Appdeamon dashboards. Since a couple of weeks the dashboards on my old iPad running iOS 9.3.5 don't work anymore. I've been watching it for a couple of weeks expecting it to be fixed soon. After all, I guess I'm not the only one who uses an old iPad for such an application. But even after the release of the new HA release, nothing has changed. The problem must be somewhere in Appdeamon because the version of iOS on the Apple has not been updated for several years.
On my laptop running Windows 10 and on an iPad 2 running iOS 14.71 everything does work just fine.
This way I can't do anything anymore with the iPad and the expensive wall-mount. 
I didn't change anything except installing the new release of HA and Appdeamon.
By the way: The log of Appdeamon doesn't show abnormalities.

## Expected behavior

> Be able to use what I designed. See camera images, see statuses of sensors and the weather. Be able to control thing by pushing the buttons. 

## Actual behavior

> I do get to see the gray squares that match my design but I don't get to see any content. No camera images, no statuses and I can no longer control anything with it. 

## Steps to reproduce

> I'm running core-2021.9.5 on a raspberry Pi 4 with Home Assistant OS 6.3. The version of Appdeamon I use is:  0.7.0 

## Proposed changes

> Is there a solution? Make it work again like it used to work a couple of weeks ago.

**Comment by teqali** [comment]
when will it work again?

**Comment by miraculixdruid** [comment]
Having exactly the same problem as mentioned above (core-2021.9.6, supervisor-2021.09.0, Home Assistant OS 6.3, AppDaemon 4.1.0)

**Comment by chiefcomm** [comment]
Anyone have any idea how this is going - I know it isn't the AppDaemon Addon but any insight to when AppDaemon will sort their stuff out would be good :-)

**Comment by miraculixdruid** [comment]
How can I rollback the AppDaemon-docker in some way on my HassOS?

**Comment by Kouwe-sudo** [comment]
It is disappointing to note that no one seems to care about the bug I reported. Normally a bug that is reported is often fixed within a few days. Sometimes even within a few hours. But with AppDeamon it seems that everyone is pointing at someone else without anything happening. I noticed that this was the same issue a few months ago with exactly the same situation where the dashboards were also empty, and that Frenck seemed to be angry about it as well. 
I wonder if such an app can still be an official addon then. 
I am now stuck with an unusable iPad an expensive Vidabox (that is only suitable for this iPad) and a hole in the wall (to pull the power supply through).

**Comment by safadig** [comment]
> It is disappointing to note that no one seems to care about the bug I reported. Normally a bug that is reported is often fixed within a few days. Sometimes even within a few hours. But with AppDeamon it seems that everyone is pointing at someone else without anything happening. I noticed that this was the same issue a few months ago with exactly the same situation where the dashboards were also empty, and that Frenck seemed to be angry about it as well.
> I wonder if such an app can still be an official addon then.
> I am now stuck with an unusable iPad an expensive Vidabox (that is only suitable for this iPad) and a hole in the wall (to pull the power supply through).

All our Samsung Displays have also been crippled!

**Comment by teqali** [comment]
will it be patch?

**Comment by frenck** [comment]
It is an upstream issue is with AppDaemom. If this will be fixed or patched is up to them. Please ask and discuss that upstream.

**Comment by ildegardes** [comment]
Same problem here ... :(

**Comment by frenck** [comment]
@ildegardes, sorry to hear that, however, please note that comments like "Same problem here" don't really add anything. Please, just don't comment in such cases. Thanks 👍

**Comment by safadig** [comment]
@frenck not sure where we should post comments on this? can you please point us to the AppDaemon discussion to post to? Thanks

**Comment by frenck** [comment]
It is linked above.

**Comment by safadig** [comment]
This fixed the problem for me.
#156 
https://github.com/AppDaemon/appdaemon/issues/1335#issuecomment-933848546

**Comment by chiefcomm** [comment]
@safadig you mentioned this adding custom widgets fixed it for you.  Are you able to explain in more detail?  What folders you copied from GitHub and to where exactly on HomeAssistant?

**Comment by safadig** [comment]
@chiefcomm copy content of directory appdaemon/appdaemon/widgets/basejavascript/ from github
[https://github.com/AppDaemon/appdaemon/tree/dev/appdaemon/widgets](url)
 to HA /config/appdaemon/custom_widgets/basejavascript
create /basejavascript as most likely it is not in custom_widgets
Restart Appdaemon

**Comment by chiefcomm** [comment]
> @chiefcomm copy content of directory appdaemon/appdaemon/widgets/basejavascript/ from github [https://github.com/AppDaemon/appdaemon/tree/dev/appdaemon/widgets](url) to HA /config/appdaemon/custom_widgets/basejavascript create /basejavascript as most likely it is not in custom_widgets Restart Appdaemon

Perfect thank you @safadig it works perfectly :-)

**Comment by PKort** [comment]
Copying basejavascript folder does not work for me - on original iPad 2010 (in Safari) and on iPhone 5 (also Safari) I still don't get any widgets working.

**Comment by auckz** [comment]
I'm having the same problem on old iPad Mini 1 (running iOS 9.3.5), copied the contents from basejavascript to my appdeamon folder and can't get widgets to work

**Comment by frenck** [comment]
Please report it upstream with the AppDaemon project... they have been holding off the release of the fix for weeks now... not much I can do about that...

**Comment by PKort** [comment]
> Please report it upstream with the AppDaemon project... they have been holding off the release of the fix for weeks now... not much I can do about that...

@frenck do you mean the fix with new files from the basejavascript folder (which does not seem to be working for me), or some other fix?

**Comment by frenck** [comment]
The fix is that they release a new version of AppDaemon. Workarounds are not a solution.

**Comment by BrunoGonc-lab** [comment]
Thank you so much @safadig! It worked for me on iPad 4 iOS 10.3.3.
I had to create the folder "custom_widgets" because it didn't exist in "/config/appdaemon/". After importing the files and restarting AppDaemon, everything was back to normal.

**Comment by teqali** [comment]
not fixed

**Comment by frenck** [comment]
Not an add-on issue either. I'm closing the issue on this end, as this is an AppDaemon issue, not an issue induced by the add-on.
