### ISSUE TITLE
Support Ingress

### ISSUE THREAD

**Issue by Gregable** [hassio-addons/app-appdaemon#157]
# Problem/Motivation

AppDaemon runs a web server on port 5050. There is no user/pass/2factor authentication for this server, so it's not secure to expose the port to the internet. It also isn't set up for HTTPS serving, so the traffic would be in the clear anyway.

## Expected behavior

If I understand correctly, the [ingress feature](https://www.home-assistant.io/blog/2019/04/15/hassio-ingress/) would solve this problem.

## Proposed changes

Support the [ingress feature](https://www.home-assistant.io/blog/2019/04/15/hassio-ingress/).

**Comment by frenck** [comment]
This add-on cannot support ingress. This is a AppDaemon limitation.
