### ISSUE TITLE
The compiled application.js does not work in some browsers

### ISSUE THREAD

**Issue by Zylazy** [hassio-addons/app-appdaemon#166]
There is a try catch block in the compiled application.js, which causes problem in some browser (also in fully kiosk browser on my tablet). The problem is that the catch has no parameters how ever it is expected. So this line
line 1267:      catch
should be replaced with this:      catch (error)

**Comment by frenck** [comment]
This is not an add-on issue, but an issue with AppDaemon itself, please report this with the AppDaemon project: <https://github.com/AppDaemon/appdaemon>
