### ISSUE TITLE
I2C Ports Access

### ISSUE THREAD

**Issue by amarce** [hassio-addons/app-appdaemon#169]
# Problem/Motivation

> When trying to access GPIO from homeassistant addon, I'm facing a permission denied issue:

`  File "/usr/lib/python3.9/site-packages/luma/core/interface/serial.py", line 73, in __init__
    raise luma.core.error.DevicePermissionError(
luma.core.error.DevicePermissionError: I2C device permission denied: /dev/i2c-1`

## Expected behavior

> Be able to access the i2c ports

## Actual behavior

> Got a permission denied error

## Steps to reproduce

> Enable I2C on hass.io and try to access the port

## Proposed changes

> Would be nice if we could get a "Protection Mode" toggle to disable the elevated system access like other addons do (Like SSH & Web Terminal or glances). This way hardware delegated to the container could be accessed if needed, and hi/low security could be selected.

**Comment by amarce** [comment]
This is related to this one:

https://github.com/hassio-addons/addon-appdaemon/issues/53#issuecomment-754508254

But with the proposed change could be left to the user choose which security he wants for his appdaemon container.

**Comment by amarce** [comment]
I can confirm that by adding to the config,json:

`  "privileged": ["SYS_ADMIN"],
  "full_access": true,
`

After restarting supervisor and core and reinstalling appdaemon, it shows the "protection mode" selector and I2C works and expected.

The downside is that the rating went down to 1  :/

**Comment by Farmbot26** [comment]
Could we not add something like this?
`
"devices": ["/dev/i2c-1:/dev/i2c-1"]  
`

**Comment by frenck** [comment]
> Could we not add something like this?

No, we cannot, as that will not work on systems that do not have that device.

**Comment by frenck** [comment]
Thanks for the suggestion, however, I do not plan on adding support for this.

If you are in need of GPIO, I would highly recommend using an ESP device instead (and decoupling it).
