### ISSUE TITLE
How to use init_commands to install python packages from a local directory?

### ISSUE THREAD

**Issue by ihaettypo** [hassio-addons/app-appdaemon#170]
Since packages are downloaded and installed after every restart, to make it more robust, I think it's better to install packages from a local directory instead.

However I'm not familiar with docker so I couldn't figure out how to do this. I figure the command should be something like:

```
system_packages: []
python_packages: []
init_commands:
  - pip install -e /path/to/package
```

But I'm not able to figure out how to refer to an outside directory inside the addon docker.

**Comment by frenck** [comment]
This is not by design of this add-on and is definitely not an issue/bug.

If you want to work around things, that is fine, but you are on your own in that case.
