### ISSUE TITLE
documentation: where is the configuration

### ISSUE THREAD

**Issue by prof7bit** [hassio-addons/app-appdaemon#186]
# Problem:

in DOCS.md it mentions right at the beginning:

```
Example add-on configuration:

log_level: info
system_packages:
  - ffmpeg
python_packages:
  - PyMySQL
  - Pillow

Note: This is just an example, don't copy and past it! Create your own!

```
Well, I would very much like to create my own but it does not mention where this file is located and how it should be named.

**Comment by frenck** [comment]
> Well, I would very much like to create my own but it does not mention where this file is located and how it should be named.

For every add-on in Home Assistant: The add-on page inside Home Assistant -> Configuration tab (next to the Documentation tab).
