### ISSUE TITLE
Can't update to 0.2.2

### ISSUE THREAD

**Issue by DavidFW1960** [hassio-addons/app-appdaemon#19]
# Problem/Motivation

> can't update. 404 error

## Expected behavior

> (What you expected to happen)

## Actual behavior

> 20-02-29 23:07:10 ERROR (SyncWorker_0) [hassio.docker.interface] Can't install hassioaddons/appdaemon-amd64:0.2.2 -> 404 Client Error: Not Found ("no such image: hassioaddons/appdaemon-amd64:0.2.2: No such image: hassioaddons/appdaemon-amd64:0.2.2").

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
I don't think you released the fix for 4.03?

**Comment by frenck** [comment]
404 mostly indicates a disk space issue.

The image is available: <https://hub.docker.com/layers/hassioaddons/appdaemon-amd64/0.2.2/images/sha256-3c76f159bafbd93aea6beacc4fb8f64552c7e88375608f565bee07126e5581d2?context=explore>

The fix provided in AppDaemon 4.0.3 is already in the add-on, hence it doesn't anything new and isn't a priority for that reason.

<blockquote><div><strong><a href="https://hub.docker.com/layers/hassioaddons/appdaemon-amd64/0.2.2/images/sha256-3c76f159bafbd93aea6beacc4fb8f64552c7e88375608f565bee07126e5581d2?context=explore">Docker Hub</a></strong></div></blockquote>

**Comment by DavidFW1960** [comment]
Thanks for your response.
I was getting 404 on the Supervisor update to 205 as well. I am using 7% of my space.
But I also could not docker exec into the Home Assistant container. I ended up rebooting the host and the supervisor immediately updated and I could update Appdaemon as well. I have no idea what went wrong or why this happened. Very weird.
Thanks for your help.
