### ISSUE TITLE
Material Design Icons outdated

### ISSUE THREAD

**Issue by R1N4x** [hassio-addons/app-appdaemon#190]
The Material Design Icon library seems to be outdated, resulting in missing icons.

So far I encountered these missing/not working icons:

`lightbulb-fluorescent-tube`
`lightbulb-fluorescent-tube-outline`
`countertop`
`countertop-outline`

Version 5.6.55 is used while 6.5.95 is available.

Is there a way to update it myself on my system?

**Comment by sinclairpaul** [comment]
You would need to log it upstream:

https://github.com/AppDaemon/appdaemon/blob/dev/appdaemon/assets/css/materialdesignicons.min.css
