### ISSUE TITLE
Unable to install python-dev

### ISSUE THREAD

**Issue by d0ugal** [hassio-addons/app-appdaemon#20]
# Problem/Motivation

Many Python packages require python3-dev to install, however I seem to be unable to install it. I think it could be argued that it should be included by default. However, some guidance on how to install it would be appreciated.

Apologies, this could be more of a question than a bug depending how you look at it.

I do think this is a regression, as installing python3-dev did work previously. I am not sure which release caused the issue as I have not been paying enough attention, but possibly either v0.2.0 or v0.2.1 (Sorry, I would normally pay more attention but I have a 5 day old!)

## Expected behavior

The following config to install python3-dev

```
system_packages:
  - python3-dev
```

## Actual behavior

```
ERROR: unsatisfiable constraints:
  python3-3.8.1-r0:
    breaks: python3-dev-3.8.2-r0[python3=3.8.2-r0]
    satisfies: world[python3=3.8.1-r0]
[14:20:02] FATAL: Failed installing package python3-dev
```

**Comment by d0ugal** [comment]
My guess would be that it is related to the change in the base image in 0.2.0?

**Comment by frenck** [comment]
The python version and dev version don't match. If you want to ensure that, you need to install both python & python-dev.

**Comment by d0ugal** [comment]
Aha, that worked! So just to be clear, for anyone that finds this, you need to do this;

```
system_packages:
  - python3
  - python3-dev
```

Thanks for that, I am not too familiar with apk.

**Comment by frenck** [comment]
I've just pushed an update to dev to upgrade Python & AppDaemon to the latest versions. Will do a release later today.
