### ISSUE TITLE
DeprecationWarning in Asyncio causing initalize errors

### ISSUE THREAD

**Issue by khmikkelsen** [hassio-addons/app-appdaemon#204]
# Problem/Motivation
Follow-up from this [issue](https://github.com/AppDaemon/appdaemon/issues/1547), which Justihar believes to be caused by an error in the updating of AppDaemon.

**Comment by frenck** [comment]
Its an error caused by incorrect usage of asyncio in the Python version this add-on runs on.

The add-on currently runs on Python 3.10.5, make sure your code is Python 3.10 compatible.
