### ISSUE TITLE
tcp or udp ports listening inside AppDaemon

### ISSUE THREAD

**Issue by miljbee** [hassio-addons/app-appdaemon#228]
# Problem/Motivation

> I need to code an udp listener in appdaemon. I run Homeassistant inside a VM with Homeassistant OS. I can't find a way to update the docker config to route the port I need to the appdaemon container.

## Expected behavior

> I would like to be able to indicate in the Homeassistant or appdaemon config the port I need to expose.

## Actual behavior

> There doesn't seem to be any way to set up a port mapping

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> In the appdaemon plugin configuration screen, there is a box where you indicate the tcp port to expose for appdaemon webui (5050/tcp). Is it possible to update this config screen to add more ports ?
Alternatively, is there some "magic" init commands to achieve this goal ?
![image](https://user-images.githubusercontent.com/637997/212531518-8f9dada7-18c8-4edc-9479-afc8eb99018c.png)

Thanks for your attention

**Comment by frenck** [comment]
> I can't find a way to update the docker config to route the port I need to the appdaemon container.

It can't.

The add-on is not designed to provide such functionality.

../Frenck
