### ISSUE TITLE
self.set_state() won't create new entity in HA 

### ISSUE THREAD

**Issue by Abragus** [hassio-addons/app-appdaemon#23]
# Problem/Motivation

I'm trying to use self.set_state to create a new entity in HA and get its state in other AD apps, but now new entity is created. No errors are logged in any AD log, that I can see. 

I asked in the official AD Discord, and neither me nor the guy that helped me was able to find any errors. Instead, it felt like there was some kind of problem with the connection between AD and HA, although this addon might have nothing to do with the problem. 

## Expected behavior

New entity should be created in HA. 

## Actual behavior

Nothing happens. 

## Steps to reproduce
This is the command I'm running:
self.set_state(entity_id = "sensor.house_mode", state = 'night', attributes = {"friendly_name": "House Mode"})

I have no ha_url or token in my appdaemon.yaml, so the addon should take care of connecting to HA? 

Will of course provide more info as needed. 

## Proposed changes

None.

**Comment by sinclairpaul** [comment]
The add on connects to the supervisor internally via the docker network, using the token provided to it at startup.  What OS are you running, any firewall that could be blocking connections?

**Comment by Abragus** [comment]
I'm running HA on hass.io on a RPi3, so I believe the connection should not be affected by any firewalls?

**Comment by sinclairpaul** [comment]
If its the standard HA install then no there should not be.  Can you post the Supervisor log?

**Comment by Abragus** [comment]
Is it HA/Supervisor/System/System log?

**Comment by Abragus** [comment]
ping

**Comment by frenck** [comment]
pong

**Comment by Abragus** [comment]
Sorry, I just wanted to make sure this thread hadn't got lost/forgotten among others.

**Comment by sinclairpaul** [comment]
The log you mentioned is the correct one, however I would recommend joining Discord (the link is in all Community addon's documentation) if you want a quicker response.

**Comment by frenck** [comment]
Besides this all, you should not inject new entities like that.
Create the actual entity in HA, and update that.

**Comment by Abragus** [comment]
> The log you mentioned is the correct one, however I would recommend joining Discord (the link is in all Community addon's documentation) if you want a quicker response.

I asked there first, and got help from @odianosen, but he couldn't find any problems with my code, which led me to believe something was wrong with the connection to HA.

**Comment by Abragus** [comment]
> Besides this all, you should not inject new entities like that.
> Create the actual entity in HA, and update that.

I did try to do that, but couldn't really find how in the HA documentation or some other website. How would I do that?

**Comment by frenck** [comment]
Those are known as the "input_*" integrations, or, if you are running Home Assistant Core 0.107: Helpers.
