### ISSUE TITLE
The AppDaemon addon fails to start without an internet connection

### ISSUE THREAD

**Issue by chatziko** [hassio-addons/app-appdaemon#235]
## Problem/Motivation

Appdaemon is vital for my HA setup, most automations depend on it. A __fully functional system without internet connection__ is also vital (that's why we use HA and not a cloud solution).

The problem is that the AppDaemon addon (re-)installs all configured alpine/python packages on every restart. So, if internet goes down, and the HA server restarts for any reason, AppDaemon will fail to start, causing chaos.

Is there any workaround for this? (apart from not using alpine/python packages, not really a solution).

## Proposed changes

I'm not sure how feasible this is given the way addons work, but packages should be installed only when the container is __created__ (after an update), or when the list is modified, and not on every single restart.

Another possibility could be to cache all downloaded packages, but it should done in a way that allows fully reinstalling without an internet connection.

**Comment by tjorim** [comment]
Duplicate of https://github.com/hassio-addons/addon-appdaemon/issues/212.

**Comment by chatziko** [comment]
Sorry I missed it.

Does HA always recreate the docker container of all addons on every restart? Seems strange, cause the core HA container is only re-created on updates (manual changes are preserved until the next update).

**Comment by chatziko** [comment]
If anyone wants to test, #237 addresses this issues by adding the option to cache packages.
