### ISSUE TITLE
Doco: Is there a "hot reload" for python code changes? (without having to restart all of AppDaemon)

### ISSUE THREAD

**Issue by callagga** [hassio-addons/app-appdaemon#246]
Can I ask is there is there a "hot reload" for python code changes? (without having to restart all of AppDaemon).  

I note from [issue 9](https://github.com/hassio-addons/addon-appdaemon/issues/9) that the restart process (which is slow) is expected behavior when you "restart" the Appdaemon plugin, so wondering what others do (i.e. what is possible) re getting faster turn around when you change say one line of python code in one of the files running on appdaemon?

**Comment by frenck** [comment]
There is no such thing in Python.

**Comment by teskanoo** [comment]
> Can I ask is there is there a "hot reload" for python code changes? (without having to restart all of AppDaemon).
> 
> I note from [issue 9](https://github.com/hassio-addons/addon-appdaemon/issues/9) that the restart process (which is slow) is expected behavior when you "restart" the Appdaemon plugin, so wondering what others do (i.e. what is possible) re getting faster turn around when you change say one line of python code in one of the files running on appdaemon?

@callagga This can be achieved using dependencies in your configuration

https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html#app-dependencies

**Comment by callagga** [comment]
Thanks @teskanoo.  I’ll look at this tonight but this seems like dépendances between multiple apps no?  The issue I’m referring to is after a restart it looks the Appdaemon plugin is taking a long time re-loading Python libraires it uses within the app..
