### ISSUE TITLE
Cant install appdaemon 4

### ISSUE THREAD

**Issue by Sluden** [hassio-addons/app-appdaemon#25]
# Problem/Motivation

Gets this error when trying to install appdaemon 4:

20-03-15 17:20:19 ERROR (SyncWorker_14) [supervisor.docker.interface] Can't install hassioaddons/appdaemon-armv7:0.2.3 -> 404 Client Error: Not Found ("no such image: hassioaddons/appdaemon-armv7:0.2.3: No such image: hassioaddons/appdaemon-armv7:0.2.3")

## Expected behavior

To have it installed

## Actual behavior

got this error:
Failed to install addon, Unknown Error, see logs

the log is at the top.

I had it installed before, then after reboot it couldnt start and got the same error msg. Then uninstalled it and couldnt install it again.

thx 

//Christoffer

**Comment by Sluden** [comment]
> Potential duplicates:
> 
> * [#22] appdaemon4 addon install error (61%)

it aint a duplicate i think

**Comment by sinclairpaul** [comment]
The 404 you see is generally caused by disk space or name resolution issues.

**Comment by Sluden** [comment]
I have disk space. 20 gb free. can install other "ADD-ONS". What do you mean with resolution issues?

thanks for the fast answer.

//Christoffer

**Comment by sinclairpaul** [comment]
Name resolution wouldn't apply if you can pull other addons.  It may be worth trying to run `ha supervisor repair` from the SSH/Web Terminal addon if you have it.

**Comment by Sluden** [comment]
Thanks. I Will try it.

**Comment by Sluden** [comment]
It didnt solve the problem. still getting this msg when trying to install:

20-03-17 11:50:39 ERROR (SyncWorker_15) [supervisor.docker.interface] Can't install hassioaddons/appdaemon-armv7:0.2.3 -> 404 Client Error: Not Found ("no such image: hassioaddons/appdaemon-armv7:0.2.3: No such image: hassioaddons/appdaemon-armv7:0.2.3").

**Comment by Sluden** [comment]
I had an old snapshot with Appdaemon3 backuped. Tried to restore it and that works greate. But still cant install appdaemon4
