### ISSUE TITLE
Allow UDP Broadcast with host network

### ISSUE THREAD

**Issue by macjoker-dev** [hassio-addons/app-appdaemon#26]
# Problem/Motivation

I want to use a module which communicates over UDP to detect devices on my physical network. Although AppDaemon uses bridged network, such a communication is not possible right now. UDP datagrams are blocked inside the container (the issue is described here: https://github.com/docker/for-linux/issues/637).

## Expected behavior

Allow UDP communication with host network.

## Actual behavior

UDP broadcast is blocked in spite of having bridged network. This is because of alpine default settings (`net.ipv4.icmp_echo_ignore_broadcasts = 1`) and the way docker uses them.

## Steps to reproduce

See more here: https://github.com/docker/for-linux/issues/637

My configuration was using `soco `module and Sonos devices:
```
>> import soco
>> print(soco.discovery.discover())
{SoCo("192.168.1.47"), SoCo("192.168.1.49"), SoCo("192.168.1.46")}
```
That works as expected when the container uses the host network. For a bridged one, the last line result is:
```
None
```

## Proposed changes

I have a successfully tested workaround with a local copy of AppDeamon which is using host network. Just one line added to `config.json`:
```
"host_network": true,
```

Another way could be forcing alpine to forward these UDP datagrams as suggested in that docker issue 637. 
- run docker with `--sysctl net.ipv4.icmp_echo_ignore_broadcasts=0` parameter or
- add line to /etc/sysctl.d/00-alpine.conf with "net.ipv4.icmp_echo_ignore_broadcasts = 0"

But these cases should be first validated to work properly and if they are achievable without changes in other projects (I haven't found a way to pass `--sysctl` option to an addon startup, e.g.).

**Comment by frenck** [comment]
Add-ons don't have control over the sysctl options.
I'm not planning on moving this add-on onto the host network.

Nevertheless, thanks for your suggestion.
