### ISSUE TITLE
Dear brother, every time I reboot, I re-download the python library,   

### ISSUE THREAD

**Issue by 1060778506** [hassio-addons/app-appdaemon#263]
My dear brother, my dear God,

Every time I restart hassos or AppDaemon

He would re-download it himself

Alpine Software Package

Python package

Can we add a button to the configuration options to decide whether to download these things automatically on the next reboot?

[Because the download speed is slow, half an hour, or the download fails, very troublesome, please]

Or some other way to keep him from downloading it again

 

![QQ截图20230714110026](https://github.com/hassio-addons/addon-appdaemon/assets/24760769/50a845a9-b5f7-4181-a3b3-91b1e8a1d92a)

`These log level also affects the log levels of the AppDaemon.

Option: system_packages
Allows you to specify additional [Alpine packages](https://pkgs.alpinelinux.org/packages) to be installed to your AppDaemon setup (e.g., g++. make, ffmpeg).

Note: Adding many packages will result in a longer start-up time for the add-on.

Option: python_packages
Allows you to specify additional [Python packages](https://pypi.org/) to be installed to your AppDaemon setup (e.g., PyMySQL. Requests, Pillow).

Note: Adding many packages will result in a longer start-up time for the add-on.

Option: init_commands
Customize your environment even more with the init_commands option. Add one or more shell commands to the list, and they will be executed every single time this add-on starts.`

# Problem/Motivation

&gt;    (Because I re-download the python library and Alpine package every time I reboot)

## Expected behavior

&gt;    (I would like to add a button switch to decide whether to re-download the software next time)

## Actual behavior

&gt;    (Nothing happened)

## Steps to reproduce

&gt;    (None)

## Proposed changes

&gt;    (None)

**Comment by 1060778506** [comment]
自己顶一下     Defend oneself

**Comment by frenck** [comment]
Yes this is intended and documented behavior. 

../Frenck
