### ISSUE TITLE
Appdaemon fails to start due to alpine update 

### ISSUE THREAD

**Issue by uorbe001** [hassio-addons/app-appdaemon#280]
# Problem/Motivation

Appdaemon fails to start due to "unable to select packages".

```
ERROR: unable to select packages:
  musl-1.2.4-r1:
    breaks: musl-dev-1.2.4-r2[musl=1.2.4-r2]
    satisfies: world[musl=1.2.4-r1]
               apk-tools-2.14.0-r2[musl>=1.2.3_git20230424]
               apk-tools-2.14.0-r2[so:libc.musl-armv7.so.1]
               isl26-0.26-r1[so:libc.musl-armv7.so.1]
               dash-0.5.12-r2[so:libc.musl-armv7.so.1]
               gcc-12.2.1_git20220924-r10[so:libc.musl-armv7.so.1]
               g++-12.2.1_git20220924-r10[so:libc.musl-armv7.so.1]
               libffi-3.4.4-r2[so:libc.musl-armv7.so.1]
               patch-2.7.6-r10[so:libc.musl-armv7.so.1]
               bash-5.2.15-r5[so:libc.musl-armv7.so.1]
               ca-certificates-20230506-r0[so:libc.musl-armv7.so.1]
```

I think this is caused by Alpine releasing a new version of the musl package, and this addon needs an update to be able to start, but I may be mistaken.

## Expected behavior

Addon starts without errors.

## Actual behavior

Addon won't start because it can't install package.

## Steps to reproduce

Start the addon with these system packages:

```
system_packages:
  - build-base
  - python3
  - python3-dev
  - py3-wheel
  - libcrypto3
  - libssl3
  - curl
  - curl-dev
  - cargo
  - libffi-dev
  - openssl-dev
```
  
## Proposed changes

Update docker image with new alpine version

**Comment by frenck** [comment]
Fixed by #279

**Comment by uorbe001** [comment]
Oh, sorry I missed that, thank you!

**Comment by uorbe001** [comment]
@frenck any clues when that will be released? I tried to find a release with that update but it doesn't seem to have been published yet.

**Comment by frenck** [comment]
no ETA. Whenever I have time.
