### ISSUE TITLE
Ingress Support

### ISSUE THREAD

**Issue by rafaborges** [hassio-addons/app-appdaemon#29]
Is [HA Ingress](https://developers.home-assistant.io/docs/hassio_addon_presentation/#ingress) support on the roadmap?

A port appended to the URL works fine, but it's always a good idea to minimize the attack surface when you have a system open to the internet.

**Comment by frenck** [comment]
No, it isn't and won't for this add-on, the AppDaemon application cannot do that due to they way AppDaemon self is built.
