### ISSUE TITLE
Update dialog in HA only shows the "Bug fixes" part

### ISSUE THREAD

**Issue by andarotajo** [hassio-addons/app-appdaemon#294]
# Problem/Motivation

I hope I'm right in creating a new issue for this but for me at least the update dialog for the add-on in Home Assistant for version 0.15.2 did not show the relevant part of the update but only the bug fix. The same happens when going to the add-on page and clicking on "Changelog".

![image](https://github.com/hassio-addons/addon-appdaemon/assets/55669170/f1b1e2b7-54bc-46f9-be3b-2aa57ec92ba6)

The release page (https://github.com/hassio-addons/addon-appdaemon/releases/tag/v0.15.2) has all the relevant information. I can imagine that people only see the bug fix and update without knowing about this breaking change, if they didn't see the 0.15.1 previously.

Not sure if that's fixable on your side though.

## Expected behavior

Update and changelog dialog include all information from the release page, in this case the "What's changed" part too.

## Actual behavior

Update and changelog dialog for the newest version (v0.15.2) does **not** include the "What's changed" part.

## Steps to reproduce

Requires not having updated to v0.15.2. I didn't have the previous version yet, maybe it's different for people coming from v0.15.1

**Comment by frenck** [comment]
> Not sure if that's fixable on your side though.

This was adjusted, hence you see it now on the releases page. I might have been to late for your instance to see.

../Frenck
