### ISSUE TITLE
HACS & AppDaemon Addon Version >= 15

### ISSUE THREAD

**Issue by joBr99** [hassio-addons/app-appdaemon#295]
# Problem/Motivation

Opening a new Issue for this, as it's kind of off topic in the other issue.

Downloading and updating AppDaemon Scripts is an important convenience feature, so it would be nice if we can find a way to keep it working. Especially for updating apps with multiple files it's way better than messing with the files directly.

With the folder change HACS stopps working as it is downloading apps to `/homeassistant/appdaemon/apps` and the appdaemon addon is no longer looking at that directory. 

Also HACS cannot download to the appdaemon folder as it's running in homeassistant and doesn't have access to the HACS Folder

## Proposed changes

This are the options that came into my mind:

1. Do the following on startup (requires to restart appdaemon after an update in HACS):

`rm -rf /config/apps/apps-from-hacs && cp -R /homeassistant/appdaemon/apps/ /config/apps/apps-from-hacs/`

2. Alternatively this could be archived by adding rsync to the container and syncing the folder though rsync every couple of minutes. 

3. I tried symlinking within the appdaemon container to the folder below /homeassistant and that one doesn't work as appdaemon is apparently not following the symlink.

AppDaemon doesn't care about the location of the Apps, they can be in a subdirectory, this way other custom apps in the apps folder are not affected.

This would allow to keep downloading AppDaemon Scripts within HACS. (with the downside that the appdaemon container is still accessing the home assistant folder)

**Comment by frenck** [comment]
> Downloading and updating AppDaemon Scripts is an important convenience feature, so it would be nice if we can find a way to keep it working.

Sorry, this add-on cannot support that. 

If you want to have that solution, this add-on is no longer the best option for you.

../Frenck
