### ISSUE TITLE
wrong Pip version

### ISSUE THREAD

**Issue by Mariusthvdb** [hassio-addons/app-appdaemon#3]
# Problem/Motivation

Had the error on AD3 too but now the my (only...) app has stopped working, I try to rule out all possible causes.
Should we update pip, and if yes, how to do so in Hassio?

> (Why the issue was filed)

see error in startup, posted below
## Expected behavior

> (What you expected to happen)

No error ;-)
## Actual behavior

> (What actually happened)
```
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
## Steps to reproduce

> (How can someone else make/see it happen)

Hassio 103.5 Rpi4 AD4 (was there on AD3 too)
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
The update for this has no effect on the working of the add-on.
The PIP version is provided by Alpine Linux and is shipped as part of Python.
