### ISSUE TITLE
Cannot start freshly installed AppDaemon

### ISSUE THREAD

**Issue by FlorinAcsinte** [hassio-addons/app-appdaemon#30]
# Problem/Motivation

> Cannot start AppDaemon

## Expected behavior

> Start AppDaemon 

## Actual behavior

> AppDaemon fails to start

## Steps to reproduce

> Fresh install of AppDaemon

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

These are the logs i got:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: AppDaemon 4
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.2.5
 You are running the latest version of this add-on.
 System: Ubuntu 19.10  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 0.109.5
 Home Assistant Supervisor: 220
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
[cont-init.d] appdaemon.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:36:06] INFO: Starting AppDaemon...
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/appdaemon/__main__.py", line 384, in main
    admain.main()
  File "/usr/lib/python3.8/site-packages/appdaemon/__main__.py", line 211, in main
    with open(config_file_yaml, 'r') as yamlfd:
FileNotFoundError: [Errno 2] No such file or directory: '/config/appdaemon/appdaemon.yaml'
[19:36:11] INFO: Starting AppDaemon...
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/appdaemon/__main__.py", line 384, in main
    admain.main()
  File "/usr/lib/python3.8/site-packages/appdaemon/__main__.py", line 211, in main
    with open(config_file_yaml, 'r') as yamlfd:
FileNotFoundError: [Errno 2] No such file or directory: '/config/appdaemon/appdaemon.yaml'
[19:36:15] INFO: Starting AppDaemon...`

**Comment by frenck** [comment]
Remove the `appdaemon` directory that currently is on your Home Assistant configuration folder and restart the add-on.

The add-on will create a new default configuration if the `appdaemon` folder is missing.

**Comment by FlorinAcsinte** [comment]
Thanks!
