### ISSUE TITLE
Error launching app which imports numpy

### ISSUE THREAD

**Issue by fboundy** [hassio-addons/app-appdaemon#300]
# Problem/Motivation

Since the 0.15.x update my app which depends on numpy fails to load. PAiring things back to a "hello world" app: it is fine without `import numpy as np` but crashes once it is included

## Expected behavior

import numpy to app if numpy is in Configuration as a python package

## Actual behavior

It looks like numpy is installed ok:
    
    s6-rc: info: service s6rc-oneshot-runner: starting
    s6-rc: info: service s6rc-oneshot-runner successfully started
    s6-rc: info: service base-addon-banner: starting
    -----------------------------------------------------------
    
     Add-on: AppDaemon
     Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
    -----------------------------------------------------------
     Add-on version: 0.15.2
     You are running the latest version of this add-on.
     System: Home Assistant OS 11.1  (amd64 / qemux86-64)
     Home Assistant Core: 2023.11.2
     Home Assistant Supervisor: 2023.11.3
    -----------------------------------------------------------
     Please, share the above information when looking for help
     or support in, e.g., GitHub, forums or the Discord chat.
    -----------------------------------------------------------
    s6-rc: info: service base-addon-banner successfully started
    s6-rc: info: service fix-attrs: starting
    s6-rc: info: service base-addon-log-level: starting
    s6-rc: info: service fix-attrs successfully started
    s6-rc: info: service base-addon-log-level successfully started
    s6-rc: info: service legacy-cont-init: starting
    s6-rc: info: service legacy-cont-init successfully started
    s6-rc: info: service init-appdaemon: starting
    Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
    Collecting numpy
      Downloading https://wheels.home-assistant.io/musllinux-index/numpy-1.26.2-cp311-cp311-musllinux_1_2_x86_64.whl (18.4 MB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.4/18.4 MB 5.7 MB/s eta 0:00:00
    Installing collected packages: numpy
    Successfully installed numpy-1.26.2
    WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
    s6-rc: info: service init-appdaemon successfully started
    s6-rc: info: service appdaemon: starting
    s6-rc: info: service appdaemon successfully started
    s6-rc: info: service legacy-services: starting
    [23:11:41] INFO: Starting AppDaemon...
    s6-rc: info: service legacy-services successfully started

But when an Appdaemon tries to load the module, this error is logged:

    23:07:01 WARNING Error: ------------------------------------------------------------
    23:11:45 WARNING Error: ------------------------------------------------------------
    23:11:45 WARNING Error: Unexpected error loading module: /config/apps/Github/test/test_app.py:
    23:11:45 WARNING Error: ------------------------------------------------------------
    23:11:45 WARNING Error: Traceback (most recent call last):
      File "/usr/lib/python3.11/site-packages/numpy/core/__init__.py", line 24, in <module>
        from . import multiarray
      File "/usr/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module>
        from . import overrides
      File "/usr/lib/python3.11/site-packages/numpy/core/overrides.py", line 8, in <module>
        from numpy.core._multiarray_umath import (
    ImportError: Error loading shared library ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ: No error information (needed by /usr/lib/python3.11/site-packages/numpy/core/../../numpy.libs/libopenblasp-r0-250824a8.3.23.so)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.11/site-packages/numpy/__init__.py", line 130, in <module>
        from numpy.__config__ import show as show_config
      File "/usr/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
        from numpy.core._multiarray_umath import (
      File "/usr/lib/python3.11/site-packages/numpy/core/__init__.py", line 50, in <module>
        raise ImportError(msg)
    ImportError: 
    
    IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
    
    Importing the numpy C-extensions failed. This error can happen for
    many reasons, often due to issues with your setup or how NumPy was
    installed.
    
    We have compiled some common reasons and troubleshooting tips at:
    
        https://numpy.org/devdocs/user/troubleshooting-importerror.html
    
    Please note and check the following:
    
      * The Python version is: Python3.11 from "/usr/bin/python3"
      * The NumPy version is: "1.26.2"
    
    and make sure that they are the versions you expect.
    Please carefully study the documentation linked above for further help.
    
    Original error was: Error loading shared library ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ: No error information (needed by /usr/lib/python3.11/site-packages/numpy/core/../../numpy.libs/libopenblasp-r0-250824a8.3.23.so)
    
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 1000, in check_app_updates
        await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
      File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
        response = future.result()
                   ^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 783, in read_app
        self.modules[module_name] = importlib.import_module(module_name)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/config/apps/Github/test/test_app.py", line 2, in <module>
        import numpy
      File "/usr/lib/python3.11/site-packages/numpy/__init__.py", line 135, in <module>
        raise ImportError(msg) from e
    ImportError: Error importing numpy: you should not try to import numpy from
            its source directory; please exit the numpy source tree, and relaunch
            your python interpreter from there.
    
    23:11:45 WARNING Error: ------------------------------------------------------------

## Steps to reproduce

> include numpy in Python packages in Config:
> add `import numpy as np` to an app

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by fboundy** [comment]
*Update:

Specifying `numpy==1.25` solves the problem and the test app initialises as expected

**Comment by frenck** [comment]
Glad you found a solution 👍
