### ISSUE TITLE
NSPanel: Configuration gone after Update.

### ISSUE THREAD

**Issue by meazzle2111** [hassio-addons/app-appdaemon#305]
# Problem/Motivation
Moved/deleted files after Update without Warning
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)
onfig files have been moved from /config/appdaemon to /addon_configs/a0d7b954_appdaemon

this mangled the apps.yaml file with over 500 lines of code for the backend config of my NSpanel.

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by catalincre** [comment]
mine to, wtf?!? Updates are to improve not to brake things.

**Comment by meazzle2111** [comment]
apparently the files are moved into a new location, howewer the suggested folder just contains "Hello World". I dont now what went wrong, however if this is really lost, i will be so fucking angry ngl. this worked for months and now its all fucked.

**Comment by Shimo** [comment]
Hit me too. This is absurd! It also looks like it messed with my secrets.yaml as it no longer contains any of my secrets. Restoring a backup didn't resolve it either. WTF did the devs do?

**Comment by xiconfjs** [comment]
Hi, restoring the backup of appdaemon addon works.

* Stop AppDaemon addon (if it's partially running)
* Homeassistant Webinterface -> Settings -> System -> Backups
* select "addon_a0d7b954_appdaemon_0.14.0" (new window opens)
* select "AppDaemon (0.14.0)" and click "Restore"
* AppDaemon reinstalls itself with v0.14.0 and is running fine again here

**Comment by asomkin** [comment]
- Disable auto update until everything is fixed

**Comment by openPhiL** [comment]
- and work on your backup strategy, anything can destroy a file, from updates to disk-errors .. I was able to recover the appdaemon using the build in backup and the files using my zfs filesystem.

**Comment by catalincre** [comment]
> Hi, restoring the backup of appdaemon addon works.
> 
> * Stop AppDaemon addon (if it's partially running)
> * Homeassistant Webinterface -> Settings -> System -> Backups
> * select "addon_a0d7b954_appdaemon_0.14.0" (new window opens)
> * select "AppDaemon (0.14.0)" and click "Restore"
> * AppDaemon reinstalls itself with v0.14.0 and is running fine again here

Not on my case. Very disappointing

**Comment by respectTheCode** [comment]
Restoring a backup didn't fix it and the addon backup doesn't contains any of the App Daemon files but the full backup does have everything in it.

**Comment by respectTheCode** [comment]
restoring the files isn't the only thing required to fix this... you must also add a symlink to get access to the new folder

https://github.com/hassio-addons/addon-appdaemon/issues/302#issuecomment-1817126673

**Comment by frenck** [comment]
Duplicate of #287
