### ISSUE TITLE
[support] subscribe app to homeassistant error logs

### ISSUE THREAD

**Issue by wilcomir** [hassio-addons/app-appdaemon#316]
Hello - this is just a support request.

I have an appdaemon app that calls a service in homeassistant, but sometimes this service can fail to execute due to several reasons.

I would like to be able to get a message to my app if an error is logged within homeassistant, possibly with some filters, so that I can implement some logic to decide whether to retry, o to perform some action on the app side.

I was not able to find any information regarding this particular topic within the documentation, therefore I am asking.

Thanks for the time and support.

**Comment by frenck** [comment]
Hi there @wilcomir 👋 

Your question is about AppDaemon itself and not the add-on. Please check the AppDaemon documentation on where to go for support on using AppDaemon itself:

<https://appdaemon.readthedocs.io/en/latest/#support>

../Frenck
