### ISSUE TITLE
schedy

### ISSUE THREAD

**Issue by morrydavis** [hassio-addons/app-appdaemon#32]
# Problem/Motivation

> seem to be missing module hass_apps_loader at least that's what I seen in appsdaemon4 log
## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This add-on does not ship with Shedy. Please report this with Shedy itself.
