### ISSUE TITLE
Appdaemon Always Shows Stopped - But It's Running

### ISSUE THREAD

**Issue by kirbyschapman** [hassio-addons/app-appdaemon#320]
# Problem/Motivation

> Appdaemon in the Add-Ons window always shows stopped. But I know it's not because all the callbacks and actions work as expected. The Log shows it started properly. Because it shows stopped, I can't restart it - if I press the Start button, the log doesn't change. The red stoplight is also on. I've restarted HASS several times, but that doesn't resolve the issue. It's the same on two instances of HASS installed on separate RPi4s. I uninstalled AD on the second RPi4 to see if there was some kind of conflict, but that didn't resolve the issue.

## Expected behavior

> Green light on, and buttons to stop or restart to show up.

## Actual behavior

> Red light stays on, no stop/restart buttons

## Steps to reproduce

> All I did was install a fresh installation of AD. I've checked it using a laptop running Win 11 and Edge Browser and a desktop running Win 11 and an edge browser. It's the same issue on the laptop using the Chrome browser.

## Proposed changes

> To work around it, I need to either: Uninstall and then reinstall AD, or change a line in the Python code and then save it. AD does what it's supposed to do and restarts that module.
 Log from the add-ons screen:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: AppDaemon
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.16.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.12.4
 Home Assistant Supervisor: 2023.12.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[08:58:19] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started

Version: 0.16.0
Hass info:
Core       2023.12.4
Supervisor 2023.12.0
Operating System 11.2
Frontend 20231208.2

**Comment by frenck** [comment]
> Appdaemon in the Add-Ons window always shows stopped.

Unfortunately, this is not in control of the add-on, but it is something the supervisor manages. Often, a full system reboot will help get the error resolved. If the issue persists, please report it to the Home Assistant Supervisor project.

../Frenck

**Comment by kirbyschapman** [comment]
I just installed all the latest updates to the OS and Core, and i'm back in business. Thanks!
