### ISSUE TITLE
ERROR Error loading secrets file: /config/secrets.yaml

### ISSUE THREAD

**Issue by xprezz** [hassio-addons/app-appdaemon#325]
# Problem/Motivation

Fresh install of appdaemon 0.16.2. When started exits with error "ERROR Error loading secrets file: /config/secrets.yaml"

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: AppDaemon
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.16.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.4  (aarch64 / odroid-n2)
 Home Assistant Core: 2024.1.2
 Home Assistant Supervisor: 2023.12.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[12:06:58] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 8, in <module>
ERROR Error loading secrets file: /config/secrets.yaml
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 417, in main
    admain.main()
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 276, in main
    if "appdaemon" not in config:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
[12:07:02] INFO: Service AppDaemon exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service appdaemon: stopping
s6-rc: info: service appdaemon successfully stopped
s6-rc: info: service init-appdaemon: stopping
s6-rc: info: service init-appdaemon successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

## Expected behavior

Start without errors

## Actual behavior

> (What actually happened)

## Steps to reproduce

Fresh install on HASSIO 
Core
2024.1.2
Supervisor
2023.12.0
Operating System
11.4
Frontend
20240104.0

## Proposed changes

I have found multiple posts on this refering to using a backup. I dont have a backup as I have never used appdaemon before. This is a fresh install.

**Comment by Aephir** [comment]
In case you solved, someone [here](https://community.home-assistant.io/t/appdaemon-wont-start-complains-about-secrets-yaml/641197/44?u=aephir) has the same problem.

If not, take a look at the thread anyway, there seems to be more activity there - maybe a solution will come?

**Comment by dweston** [comment]
@Aephir  is referring to me. I'm also experiencing the exact same symptoms with my `appdaemon` install. In my case I'm running Home Assistant as HA OS, with a base installation that has been in constant use in its present manifestation since circa 2018. I was running HA version 2024.1.5 when reporting the `secret.yaml` access issues.

I've upgraded to version 2024.2.1 and the same errors are being reported in the logs:

```
s6-rc: info: service legacy-services successfully started
ERROR Error loading secrets file: /homeasistant/secrets.yaml
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 417, in main
    admain.main()
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 276, in main
    if "appdaemon" not in config:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
[14:00:45] INFO: Service AppDaemon exited with code 1 (by signal 0)
```
