### ISSUE TITLE
Appdaemon wo't start

### ISSUE THREAD

**Issue by Kouwe-sudo** [hassio-addons/app-appdaemon#33]
# Problem/Motivation
I use the standard AppDaemon add-on. I didn't change anything. But it stops with an error. Perhaps I is just me being stupid and not reading the documentation careful enough. I that case I'm sorry, but then it would perhaps still be helpful to make the instruction more explicit.

> (Why the issue was filed)

## Expected behavior
This is what the log says:
18:29:12] INFO: Starting AppDaemon...
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/appdaemon/__main__.py", line 384, in main
    admain.main()
  File "/usr/lib/python3.8/site-packages/appdaemon/__main__.py", line 211, in main
    with open(config_file_yaml, 'r') as yamlfd:
FileNotFoundError: [Errno 2] No such file or directory: '/config/appdaemon/appdaemon.yaml'

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce
This is what I use:

Add-on: AppDaemon 4
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.2.6
 You are running the latest version of this add-on.
 System: HassOS 4.10  (armv7 / raspberrypi3)
 Home Assistant Core: 0.111.1
 Home Assistant Supervisor: 227
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
The first time when I got this error I thought: No problem and I added the file /config/appdaemon/appdaemon.yaml myself. But still the same error.
Perhaps that's something you should add to the instruction?

**Comment by frenck** [comment]
`/config/appdaemon/`. sound like that directory exists but is missing the appdaemon.yaml file?

Maybe remove or rename that folder. After that, it should start without problems.
