### ISSUE TITLE
Is there actually setup instructions someplace??

### ISSUE THREAD

**Issue by jake5253** [hassio-addons/app-appdaemon#330]
Where the heck are the instructions at?! The documentation from HASS says to go look at the appdaemon docs, the appdaemon docs say to go look at HASS docs. Specifically, at no point, ever, as far as I can tell, does any bit of top level documentation suggest where the f*** appdaemon.yaml goes... or if it's already made, in which case, where the hell to access it.  HASS is great, but the documentation sucks, frankly.  It often spends time explaining what it *can* do, but not *how* to do it, and that's really discouraging.

**Comment by frenck** [comment]
Hey m8 👋 

Thanks for opening up an issue. However, the tone you put up in this issue; makes me not want to help you at all.

Wish you all the best.

../Frenck


(Ps this is not an Home Assistant project)

**Comment by jake5253** [comment]
I sincerely apologize about my tone. I'm just frustrated. That's not an excuse, it's a character flaw, and I understand and respect your decision to not help me. If you choose, you may stop reading at this point, the remainder is my situation and why I'm frustrated, and a hopeful attempt at a positive outcome for my benefit and the benefit of future HASS/AppDaemon users.

I've been going around in circles attempting to figure out how to use appdaemon and i just end up back at the start looking at a page that says to check the other documentation. I shouldn't have said the documentation sucks.  It is, in general, adequate documentation -- once you find it. So maybe I should have instead said that the documentation is sometimes difficult to navigate. And this isn't an entirely baseless claim, the AppDaemon add-on is the third instance I have encountered, of what I'll call "shadow documentation", that is to say, the documentation likely exists, somewhere, it's just not immediately obvious where that is.  It's just that I would have expected to find a link within one of the first few pages to which I was exposed, about the requirements to achieve a base, connected, and operational link between Home Assistant and AppDaemon.  

The add-on documentation (where the Install button is) says "Please note, the add-on is pre-configured to connect with Home Assistant." Okay, we're installed and connected. Check one and two! 

Next, it says "This add-on does not configure the AppDaemon or HADashboard for you."  Oh. That kind of contradicts the previous statement, or at minimum it's a little bit confusing... unless... Oh! Okay, it configures just the *connection* between the two. Alright, alright that's cool. Now, check two! 

Then, it states "The configuration of the AppDaemon can be found in the add-on configuration folder of this add-on." Where's that? I'm still new to Home Assistant and largely of Docker; I get the concept of containers and I understand the idea of using mount points within containers, but I'm not sure where the configuration/folder of this add-on is.  I have the File editor add-on installed, it should be there with the other configuration files, right?  Well, no. It's not there. Alright, let's look at the AppDaemon docs then. 

"AppDaemon uses the /conf directory to store its configuration data." Then it goes into how to create and mount it within a container -- but we already have at least the connection between HASS and AppDaemon, so that must already be done, right?  Scan through the rest of that page, I see some path names, so let's ssh in... "ls /conf" -- doesn't exist. "ls ~/.homeassistant/" -- doesn't exist. "ls /etc/appdaemon" -- no.  

So, I'm lost.  Again, I apologize for being an ass. I hope you can help me and future users by clarifying the steps needed.
Thank you for all your hard work!

**Comment by sinclairpaul** [comment]
If you want to use File Editor:

![image](https://github.com/hassio-addons/addon-appdaemon/assets/24625998/06640cd9-e28e-4daf-9d70-15f305e3aae3)

You may need to toggle the config switch for Enforce Basepath with the Config

**Comment by jake5253** [comment]
Ohhhhhhh!  Awesome!  Thanks!  I hope I don't overstep any boundaries here, but I have gone ahead and created a pull request which adds that tip to the add-on docs.
