### ISSUE TITLE
AppDaemon's Hassio configuration file location isn't clear

### ISSUE THREAD

**Issue by e3e6** [hassio-addons/app-appdaemon#343]
Would be great if this behaviour would be highlighter in readme, so HASSIO users we aware of this and not spend a lot of time trying to figure this out, as this is not mentioned not in github nor on AppDaemon site.

> With this release, the appdaemon data folder will migrate/move out of the Home Assistant configuration folder into a dedicated folder for this add-on. You can access add-on configuration folders using SSH, Samba, VSCode, and similar add-ons by accessing the addon_configs folder/share.

https://github.com/hassio-addons/addon-appdaemon/releases/tag/v0.15.0

**Comment by frenck** [comment]
This is general working/feature of Home Assistant, not specific to this add-on.

Please consult the Home Assistant documentation on how Home Assistant works instead.

../Frenck
