### ISSUE TITLE
appdaemon addon broken updating from 14.0 to 16.0 + files dissapeared --> We need to avoid more people doing this!

### ISSUE THREAD

**Issue by Domigome** [hassio-addons/app-appdaemon#346]
Of course I have see the other issues, but they are now locked to further comments.

I really think not every single person should get the addon and their homes broken by updating, and then go find the solution(s) in a 150+ comment thread.

After months (years?) using this wonderful addon without issues... bad luck the moment I clicked updated.

Is there any way we could make the updates not to break?

**Comment by frenck** [comment]
> Is there any way we could make the updates not to break?

It was published as a breaking change.

All data has been migrated to the new locations Home Assistant uses for these things.

../Frenck
