### ISSUE TITLE
Documentation seems outdated

### ISSUE THREAD

**Issue by jonnybergdahl** [hassio-addons/app-appdaemon#355]
# Problem/Motivation

I recently installed this add-on, and tried to follow the docs.MD file. I got to the "edit the yaml" part where I got lost, so I googled around. Google seems to only return outdated info pointing to a '/appdaemon' inside of Home Assistant. 

There is nothing in that doc file that tell you how to access any of the files of AppDaemon, not even the smallest hint. 

## Expected behavior

I expect the docs to actually tell me what I need to get the add-on up and running.

## Actual behavior

You get nowhere close to a solution.

## Steps to reproduce

1. Try it

**Comment by frenck** [comment]
Just check, the documentation is correct and up to date.

![CleanShot 2024-11-22 at 19 53 12@2x](https://github.com/user-attachments/assets/66138d9b-4404-48f8-a02d-4e261448309f)

The configuration files of this add-on can be found in the add-on configuration folder Home Assistant exposes.

../Frenck

**Comment by jonnybergdahl** [comment]
Problem is that all other add-ons I use have their "add-on folder" placed inside of the HA config folder, thus making it very easy to access it with a text editor inside of HA. There is no indication in the docs that this add-on does not follow that practice. And as I stated, if you Google this most hits tells you that the "add-on folder" is inside of HA.

The minimum I would expect here is something at least pointing me in how to access this "add-on folder".

**Comment by frenck** [comment]
> Problem is that all other add-ons I use have their "add-on folder" placed inside of the HA config folder,

That would be a bad practice; you should report that with those add-ons. That folder is meant for Home Assistant's own configuration, not add-ons.

> The minimum I would expect here is something at least pointing me in how to access this "add-on folder".

That would be an Home Assistant documentation thing, not add-on. Home Assistant provides the folders this add-on uses.

../Frenck
