### ISSUE TITLE
Stupid question: where to find the logfiles of the Addon? It is not where appdaemon stand alone usually creates / expects them

### ISSUE THREAD

**Issue by bachmarc** [hassio-addons/app-appdaemon#358]
Hi,
you did  great job to integrate appdaemon (including the logs) into HA.
I found the logs under /system/lods/appdaemon in the HA UI... 

But what is the folder? I want to add per-app logfiles and keep them in same folder but appdaemon says "not able to write non existing file"... I could create.... but where?
The apps are stored the original way but the logs are moved to unknown path, with unknown config trick...

there are pros and cons:
The AppDaemonUI is not showing logs anymore... a pity.
I cannot use tail in a console
All differs now from documentation of appdaemon
I do not know where to create individual logfiles without specifying full path

Regards Marc

**Comment by frenck** [comment]
> But what is the folder?

There is no folder, it logs out via Docker, which is logged into journald by HAOS; the Home Assistant frontend queries/shows the contents of journald, including a live view.

> I cannot use tail in a console

You can, the `ha logs` command has a `--follow` flag.

../Frenck
