### ISSUE TITLE
Upgrade from 4.0.3 to 4.0.4 does not appear to be an option

### ISSUE THREAD

**Issue by grantclem** [hassio-addons/app-appdaemon#41]
# Problem/Motivation

> Does not appear to be an upgrade option for the latest AD release

## Expected behavior

> N/A

## Actual behavior

> N/A

## Steps to reproduce

> N/A

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Correct, it requires an add-on release which is pending.
