### ISSUE TITLE
HADashboard on Old Ipad Mini No longer Syncing States

### ISSUE THREAD

**Issue by jeremeyi** [hassio-addons/app-appdaemon#46]
I updated the AppDaemon 4 add-on to add-on version 0.3.0 today (was running a version behind this before) and now HADashboard is not syncing states on an old Ipad Mini I am using as a control panel.  It works fine on Chrome on this mini but not Safari (which is what I normally use because of full screen mode when launching from a home screen shortcut).  If I load it in Safari from the address bar and not from the home screen shortcut I get "error getting state, check Java Console for details".  If I launch it from the shortcut it loads fine but only shows states of entities at the time of loading and never updates after that.  If it is finally time for me to retire this Ipad I am fine with that, just wanted to give a heads up, and hopefully there is a fix.

**Comment by frenck** [comment]
Add-ons wrap existing applications. Please report this issue with the ApPDaemon project.

Thanks 👍
