### ISSUE TITLE
iFrame not showing properly on tablet

### ISSUE THREAD

**Issue by mspace00** [hassio-addons/app-appdaemon#48]
# Problem/Motivation

iFrame not showing properly on tablet. When using an iFrame to stream mjpeg camera feed, the desktop browser works perfectly (Firefox and Chrome). On a Samsung tab A the iFrame shows black with download button and play icon.

## Expected behavior

See iFrame behave on tablet the same as on desktop browser

## Actual behavior

iFrame shows all black with play icon and download button. Verified on Samsung browser, Chrome, and Fully Kiosk.

## Steps to reproduce

stream an mjpeg stream thru iFrame on a tablet

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Hi there @mspace00!

Thanks for opening an issue. Add-ons wrap existing applications, in this case: AppDaemon.
We don't develop the application itself, we develop and maintain the wrapper. If you have issues with the application, please report the issue with AppDaemon itself.

Thanks 👍
