### ISSUE TITLE
Deprecated warnings in log on restart.

### ISSUE THREAD

**Issue by Bas-Man** [hassio-addons/app-appdaemon#52]
# Problem/Motivation

Unexpected warning in log.

## Expected behavior

Clean exit and restart

## Actual behavior

From logs:
2020-12-15 22:44:17.187047 INFO AppDaemon: AppDaemon is stopped.
/usr/lib/python3.8/site-packages/appdaemon/__main__.py:133: DeprecationWarning: Task.all_tasks() is deprecated, use asyncio.all_tasks() instead
  pending = asyncio.Task.all_tasks()
/usr/lib/python3.8/site-packages/aiohttp/connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
/usr/lib/python3.8/asyncio/events.py:81: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._context.run(self._callback, *self._args)
/usr/lib/python3.8/asyncio/events.py:81: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._context.run(self._callback, *self._args)
/usr/lib/python3.8/site-packages/aiohttp/connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(

## Steps to reproduce

Running under latest OS 5.8 and latest Hassio update. 2020/12/15(Tokyo)

## Proposed changes
None

**Comment by frenck** [comment]
This is an issue with AppDaemon itself, not the add-on. Please report your issue upstream.

Thanks 👍
