### ISSUE TITLE
GPIO access on the Raspberry Pi

### ISSUE THREAD

**Issue by davidhitchins** [hassio-addons/app-appdaemon#53]
I hope this is an ok place to pose this question @frenck 

Like a number of others on this forum and elsewhere, I have been trying to use 
Appdaemon on a Raspberry pi to read data from GPIO pins and use it in Home Assistant.

In my case I'm trying to read the codes received by a 433MHz receiver attached to the pi
to GPIO PIN 27 using the rpi_rf module's rpi-rf_receive.py script
(https://github.com/milaq/rpi-rf/blob/71fbe0507588cadd0e58978d2ed72a3cb5994f16/scripts/rpi-rf_receive)

But no luck as I keep getting this error:
  File "/usr/lib/python3.8/site-packages/rpi_rf/rpi_rf.py", line 188, in enable_rx
    GPIO.setup(self.gpio, GPIO.IN)
RuntimeError: No access to /dev/mem.  Try running as root!

Firstly, in my setup (Hass.io 32 bit for Raspberry pi 3b) there is no such directory as
/dev/mem
There is however this one
/sys/class/gpio
and when I enable the Raspberry PI GPIO integration in the configuration.yaml for pin 27
the folder GPIO27 appears in the above directory and events accrue in Home Assistant's database.

It seems to be a permissions problem for AD apps accessing the GPIO pins of the pi.
So then I wondered what user Appdaemon apps run under and could I elevate that user's permissions?

According to this little App I wrote it is actually the root user!
But root must have access to the GPIOs musn't it?
Or is this a red herring?
And isn't the advice not to run Appdaemon under the root user?

```
import appdaemon.plugins.hass.hassapi as hass
import os
import pwd

class DetectMotion(hass.Hass):
    
    def initialize(self):
        self.log("ok WE GOT THIS FAR now................")
        self.listen_now()

    def listen_now(self):
        self.log(pwd.getpwuid( os.getuid() )[ 0 ])
```
By the way I do have this in my Appdaemon configuation and all appears to go well according to the 
Appdeamon logs.
```
system_packages: []
python_packages:
  - argparse
  - datetime
  - RPi.GPIO
  - rpi_rf
init_commands: []
```
Is there any way to fix this permissions problem without having to set up Home Assistant using venvs
or more complex onboarding?

Thanks in advance.

**Comment by frenck** [comment]
The mapping for `/dev/mem` is missing in this add-on, that is simply a bug.

> According to this little App I wrote it is actually the root user!
> But root must have access to the GPIOs musn't it?
> Or is this a red herring?
> And isn't the advice not to run Appdaemon under the root user?

That application is isolated on a container level. It is all running in its own isolated and limited world.

**Comment by davidhitchins** [comment]
Guess I will go along the path of installing HA and AD in their own separate VENVS on the same Raspberry pi. Looks like this might be the better approach in the end. But I am still curious why my Appdaemon app can't access the GPIO pins when HA can. Different user? Let me know if there's a better place for this discussion than here. Your creation of AD is much appreciated; I am even a sponsor on Patreon because of it.

**Comment by frenck** [comment]
> Guess I will go along the path of installing HA and AD in their own separate VENVS on the same Raspberry pi. Looks like this might be the better approach in the end. 

That is a personal opinion and not really a concern for the add-on or anything in this issue.

> But I am still curious why my Appdaemon app can't access the GPIO pins when HA can. Different user?

No, you are thinking of a single computer/OS scope. We are dealing with isolated runtimes/containers here, they do not work like that. Not completely correct, but easiest to understand how it works: Each add-ons/container/part in this setup runs on its own little mini-computer. So, Home Assistant Core runs its own container with its own operating environment, so does any other add-on.

In this case, the add-on misses an instruction for the supervisor to give access to `/dev/mem` on this container (machine). Thus, it simply doesn't have it and is not user permission related.

To be clear, this is a configuration error in this add-on, thus a bug. I need to fix this and release a new version of the add-on.

**Comment by davidhitchins** [comment]
Thanks for these clarifications. Does this mean that when the /dev/mem bug is fixed then it will work?

**Comment by frenck** [comment]
I've looked further into this case, it is not just mem that is missing, it is the whole permission model need to be drastically lowered in order to provide access to GPIO.
For example, the need for disabling AppArmor, raw IO access and the gpio access as a whole are all missing (and the /dev/mem as well).

Adding this, will lower the rating of this add-on significantly and adds additional risks. Considering this is the first request I ever for GPIO on AppDaemon in all these years I maintain an AppDaemon add-on: I'm going to friendly decline adding support for this.
