### ISSUE TITLE
Selenium and Chromedriver

### ISSUE THREAD

**Issue by akeslo** [hassio-addons/app-appdaemon#70]
# Problem/Motivation

Attempting to use AppDaemon with Selenium.  Unable to find chromedriver

## Expected behavior

Python script runs without issue

## Actual behavior

2021-01-30 20:52:17.662481 WARNING oil: ------------------------------------------------------------
2021-01-30 20:52:17.661821 WARNING oil: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 933, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/oil.py", line 19, in check_oil
    browser = webdriver.Chrome('chromedriver')
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

## Steps to reproduce

Run a python script witch uses selenium

**Comment by frenck** [comment]
have you installed it?

**Comment by akeslo** [comment]
I'm having trouble getting it installed, I'm running hass.io on raspberry pi 4

The driver is placed in chromedriver in /usr/local/bin

**Comment by frenck** [comment]
I'm not sure if I follow...
Could you share your add-on configuration? (Supervisor panel -> Click AppDaemon -> Configuration tab)

**Comment by akeslo** [comment]
![image](https://user-images.githubusercontent.com/3003773/106386529-6a597a00-63a3-11eb-9895-9be51f605b6e.png)

**Comment by frenck** [comment]
> The driver is placed in chromedriver in /usr/local/bin

So, where is the part where you placed the driver in there?

**Comment by akeslo** [comment]
> > The driver is placed in chromedriver in /usr/local/bin
> 
> So, where is the part where you placed the driver in there?

I sftp’ed the driver to that location on the file system. What should I be listing here?

**Comment by frenck** [comment]
There is no SSH running in this container... How would one sftp it into that location?

My current guess, in that case, is that you uploaded something to the host of your machine... which is not the same namespace.

**Comment by akeslo** [comment]
> There is no SSH running in this container... How would one sftp it into that location?
> 
> 
> 
> My current guess, in that case, is that you uploaded something to the host of your machine... which is not the same namespace.

ok - yes it was to the host. 

Can selenium be used in this container?

**Comment by frenck** [comment]
You could try to install the chromium driver compiled against musle provided by the Alpine Edge repository, but your mileage may vary https://pkgs.alpinelinux.org/package/edge/community/aarch64/chromium-chromedriver

**Comment by frenck** [comment]
Closing issue, as it is running stale.
