### ISSUE TITLE
Intermittent issue with calling the notify service within AD.

### ISSUE THREAD

**Issue by grantclem** [hassio-addons/app-appdaemon#71]
# Problem/Motivation

> Appears to be an issue since the latest AD release where the notify service (and a few others) do not initiate when called. Testing through HA services tab proves it works fine narrowing the problem with AD. Currently running 2021.2.b1 and Addon v0.4.1

`2021-02-01 09:33:00.045414 WARNING AppDaemon: Unknown domain (default/notify) in call_service from test`

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

No way to re-produce 
> (How can someone else make/see it happen)

## Proposed changes

Currently the only way the fix the issue is to restart the AD add-on

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
> No way to re-produce

No way to fix

I can't fix something I can't analyze.

**Comment by grantclem** [comment]
Great response, no I cannot re-produce the error when asked. Only wait for it re-occur.
