### ISSUE TITLE
installing python-dev broken in newest release

### ISSUE THREAD

**Issue by frog32** [hassio-addons/app-appdaemon#85]
# Problem/Motivation

Installing python3-dev fails since newest release.

## Expected behavior

To either work or to be able to downgrade to the last working release.

## Actual behavior

Installation breaks because of dependency issues, downgrade seems to be not an option.

## Steps to reproduce

1. add python3-dev to system-packages
2. start addon

## Logs

> ERROR: unable to select packages:
  python3-3.8.7-r0:
    breaks: python3-dev-3.8.7-r1[python3=3.8.7-r1]
    satisfies: world[python3=3.8.7-r0]
               py3-urllib3-1.26.2-r1[python3]
               py3-cachecontrol-0.12.6-r0[python3]
               py3-webencodings-0.5.1-r3[python3]
               py3-requests-2.25.1-r1[python3]
               py3-colorama-0.4.4-r0[python3]
               py3-toml-0.10.2-r0[python3]
               py3-pip-20.3.4-r0[python3]
               py3-msgpack-1.0.2-r0[python3]
               py3-pep517-0.9.1-r0[python3]
               py3-contextlib2-0.6.0-r0[python3]
               py3-setuptools-51.3.3-r0[python3]
               py3-chardet-4.0.0-r0[python3]
               py3-parsing-2.4.7-r1[python3]
               py3-packaging-20.9-r0[python3]
               py3-ordered-set-4.0.2-r0[python3]
               py3-idna-3.1-r0[python3]
               py3-pytoml-0.1.21-r0[python3]
               py3-appdirs-1.4.4-r1[python3]
               py3-lockfile-0.12.2-r3[python3]
               py3-distro-1.5.0-r1[python3]
               py3-retrying-1.3.3-r0[python3]
               py3-distlib-0.3.1-r1[python3]
               py3-six-1.15.0-r0[python3]
               py3-progress-1.5-r0[python3]

**Comment by frenck** [comment]
always install `python` package itself as well. That will prevent this issue for you.
