### ISSUE TITLE
Python requirements are reinstalled on every start

### ISSUE THREAD

**Issue by frog32** [hassio-addons/app-appdaemon#9]
# Problem/Motivation

Installing python dependencies is slow and if those dependencies require some C to be compiled it is even slower.

## Expected behavior

We are already checking https://wheels.hass.io/alpine-3.11/armv7/ (rpi4 32bit) for available wheels. However the actual number of wheels is limited and there is no obvious way to add additional wheels.

## Actual behavior

These get installed from source and take >15 minutes in my case of just having google-cloud-logging.

## Steps to reproduce

Define google-cloud-logging as dependency. This requires libstdc++ build-base python3-dev to compile the dependencies.

## Proposed changes

One possible way would be to allow an additional wheel cache locally or provide a way to allow people to nominate wheels for the hass.io server.

<blockquote><div><strong><a href="https://wheels.hass.io/alpine-3.11/armv7/">Index of /alpine-3.11/armv7/</a></strong></div></blockquote>

**Comment by frenck** [comment]
That is not a bug and expected behavior.
Add-ons are non-persistent containers. Anything installed is gone after a restart.

This add-on is not in control of the wheels cache.

**Comment by frog32** [comment]
Adding a persistent wheel cache option locally would totally fix this or being able to override the default wheel cache option to be able to change it. How it is now I almost have to fork this addon and build it with my requirements built in which definitely is not the right way to go. Is the python requirements config not meant to be used or am I doing something else wrong?

**Comment by frenck** [comment]
You can do so if you feel like doing that using the `init_commands`.

> How it is now I almost have to fork this addon and build it with my requirements built in which definitely is not the right way to go.

It are docker images, sure that is the right way. Build on top of previous containers.

> Is the python requirements config not meant to be used or am I doing something else wrong?

This has nothing to do with requirements?

**Comment by frog32** [comment]
So I managed to build all the wheels required but init_commands only gets run after pip install. Any chance that adding an other --find-links that is configurable? This would allow others to do the same (build wheels locally and store them somewhere where they can link to them).
