### ISSUE TITLE
Icon widget broken by 4.0.6

### ISSUE THREAD

**Issue by lancasterJ** [hassio-addons/app-appdaemon#96]
# Problem/Motivation

Icon widget stopped displaying the icon and state text when upgraded to 4.0.6

## Expected behavior

> (What you expected to happen)

![image](https://user-images.githubusercontent.com/63460573/112539445-ea4eff80-8da8-11eb-9a7c-bfe819f5085f.png)

## Actual behavior

> (What actually happened)
![image](https://user-images.githubusercontent.com/63460573/112539277-b4118000-8da8-11eb-9529-c958e12e7392.png)

## Steps to reproduce

garbage:
    widget_type: icon
    entity: sensor.garbage
    title: Garbage
    title2: collection
    state_text: 1
    icons:
      "today":
        icon: mdi-delete-circle
        style: "color: blue"
      "tomorrow":
        icon: mdi-delete-restore
        style: "color: black"
      "default":
        icon: mdi-delete-empty
        style: "color: white"

Commenting out the "default" section display the state text but no icon because there is no match.

garbage:
    widget_type: icon
    entity: sensor.garbage
    title: Garbage
    title2: collection
    state_text: 1
    icons:
      "today":
        icon: mdi-delete-circle
        style: "color: blue"
      "tomorrow":
        icon: mdi-delete-restore
        style: "color: black"
      # "default":
        # icon: mdi-delete-empty
        # style: "color: white"

![image](https://user-images.githubusercontent.com/63460573/112539932-824ce900-8da9-11eb-93ba-5f24de41a679.png)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
The addon wraps the software, so you would likely be better seeking help on the Appdaemon discord or at https://github.com/AppDaemon/appdaemon
